-- 005

local builder = utaha.uiBuilder
local alignment = utaha.alignment

return builder:beginLayout()
    :paddingSize(1)
    :verticalAlignment(alignment.ALIGN_LEFT_OR_TOP)
    :horizontalAligment(alignment.ALIGN_LEFT_OR_TOP)
    :beginRow(alignment.ALIGN_LEFT_OR_TOP)
        :add(builder:beginFlatMenuGroup("test.a")
            :beginColumn("汉字", 1)
                :addItem("条目1", 2, nil)
                :addDiv()
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
            :endColumn()
            :beginColumn("汉字", 1)
                :addItem("条目1", 2, nil)
                :addDiv()
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
            :endColumn()
            :beginColumn("汉字", 1)
                :addItem("条目1", 2, nil)
                :addDiv()
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
            :endColumn()
            :beginColumn("汉字", 1)
                :addItem("条目1", 2, nil)
                :addDiv()
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
                :addItem("条目2", 3, nil)
            :endColumn()
        :endMenuGroup())
        :add(builder:beginFlatButton("test.b")
            :text("按键")
            :w(48)
            :h(24)
        :endButton())
        :add(builder:beginFlatInputBox("test.c")
            :w(128)
            :h(24)
        :endInputBox())
    :endRow()
:endLayout()